Aanpassingen voor 2019
fris-fruitig/eerstekerstborrelvanhetjaar.nl pull request #4
Opened 2018-12-05 17:24 UTC by rvanderveen

- Datum aangepast
- Logo's aangepast (hi,hi guide toegevoegd als organisator)

Todo:
- [ ] https activeren op eerstekerstborrelvanhetjaar.nl

2018-12-06 08:06 UTC, luukdv commented on index.html
> +    <title>Eerste kerstborrel van het jaar | Fris & Fruitg + the cee spot</title>
Er staat nog steeds `Fruitg`

2018-12-06 19:06 UTC, sprmn requested changes
zie opmk luuk

2018-12-07 17:01 UTC, antek-drzewiecki commented
Ship it :ship: !!!!

2018-12-07 17:01 UTC, antek-drzewiecki commented
Please use another term for whitelist / blacklist, this is racist.

2018-12-07 17:01 UTC, antek-drzewiecki commented
Also master/slave.

2018-12-07 17:02 UTC, antek-drzewiecki commented
@luukdv @sprmn @rvanderveen @arthurvi @antek-drzewiecki  @sjoerd :ship:  @harald

2018-12-07 17:03 UTC, antek-drzewiecki commented
@michellederooij hallo

2018-12-07 17:03 UTC, antek-drzewiecki commented
@sboerrigter

2018-12-07 17:04 UTC, antek-drzewiecki commented
@brtld

2018-12-11 08:56 UTC, luukdv approved these changes
Goed

2018-12-12 11:28 UTC, rvanderveen commented
@sprmn

2018-12-12 13:04 UTC, sprmn commented
![image](https://user-images.githubusercontent.com/9630313/49871561-dc168880-fe16-11e8-83e1-8e5add764100.png)
not ok

2019-01-09 16:31 UTC, merged